# Generated by Django 5.2.4 on 2025-07-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatcontact_unread_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontact',
            name='contact_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
