# Generated by Django 5.2.4 on 2025-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatcontact_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontact',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
