# Generated by Django 5.2.4 on 2025-08-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatcontact_last_message_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontact',
            name='contact_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
