# Generated by Django 5.2.4 on 2025-08-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatcontact_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatcontact',
            name='contact_photo',
        ),
    ]
